### ISSUE TITLE
O projeto ainda é necessário?

### ISSUE THREAD

**Issue by alexandre-mbm** [josecoelho/bbvisa2ofx#13]
Hoje, no Internet Banking, encontrei uma exportação em OFX, para cada cartão.

**Comment by LeoFCardoso** [comment]
Eu continuo usando o projeto, pois a geração nativa de OFX: (i) não considera conversão para dólar, (ii) não faz o ajuste das datas em compras parceladas.

**Comment by alexandre-mbm** [comment]
Caso necessário, também vou usá-lo. Você pode me falar mais dessas duas questões?

**Comment by jfneis** [comment]
Alexandre, baixando um arquivo com gastos em dólares e compras parcelas e,
em paralelo, convertendo o TXT para OFX usando o bbvisa2ofx você consegue
ver certinho as diferenças.

1. Gastos em dólares: o bbvisa2ofx converte pela cotação da fatura os
gastos para reais. O OFX do site, se não me engano, não faz a conversão,
então você fica com valores zerados dependendo da ferramenta (no gnucash
fica);
2. Compras parceladas: nas parcelas depois da 1a (ex.: 02/06, 03/06, etc.),
o bbvisa2ofx adiciona um mês por parcela-1. Ou seja: se sua compra foi na
data de 10/08, por exemplo, a 2a parcela será convertida como sendo em
10/09, a terceira como 10/10, etc. Isso ajuda a manter o controle de quanto
você desembolsou naquela fatura. No OFX do site ele mantém a data original
da compra, que é como vem no extrato também. Seria algo como regime de
caixa (bbvisa2ofx) x regime de competência (OFX do site).

Abraço!

Em ter, 27 de dez de 2016 às 16:39, Alexandre Magno <
notifications@github.com> escreveu:

**Comment by alexandre-mbm** [comment]
Não sei o que é "regime de caixa" vs. "regime de competência". Por que essa mexida nas datas não tornará a conciliação inconsistente? Quero usar o GnuCash para conciliar com o extratos reais anotações exportadas de smartphones. Está errado?

**Comment by jfneis** [comment]
Não uso as anotações de smartphone do GnuCash, então não sei te dizer se
ele usa a data como chave. Mas você pode testar 1 compra pra testar.

Caixa e competência são conceitos contábeis.

Em ter, 27 de dez de 2016 às 17:12, Alexandre Magno <
notifications@github.com> escreveu:

**Comment by alexandre-mbm** [comment]
O teste de conciliação que já fiz não levou em consideração dados reais advindos do home banking. Farei isso quando tiver tempo, pois é o que quero usar. Infelizmente hoje a máquina apresentou um defeito de hardware, então vou precisar me afastar um pouco.

**Comment by jfneis** [comment]
@alexandre-mbm se tiver a resposta se o teste continua funcionando mesmo com a funcionalidade de mudança de data, avisa aqui pra ficar registrado, por favor! abs!

**Comment by alexandre-mbm** [comment]
@jfneis, estou um tanto preocupado com outros assuntos; demorarei a voltar aqui.

**Comment by josecoelho** [comment]
Opa! Fico feliz que continuam usando o projeto. Se eu puder ajudar em alguma coisa é só dar um toque.

Vou deixar o ticket aberto até que o @alexandre-mbm tenha a oportunidade de testar novamente e nos dar um retorno. :)

Atualizei a versão [web](http://bbvisa2ofx.josecoelho.com/) da app adicionando as duas funcionalidades levantadas pelo @jfneis. Obrigado mestre.

Sugestões serão sempre bem vindas.
