### ISSUE TITLE
Sugestão Fernando: Somar IOF junto com gastos internacionais.

### ISSUE THREAD

**Issue by josecoelho** [josecoelho/bbvisa2ofx#4]
Fernando Eduardo Barreira ( https://www.facebook.com/fernandoeduardocbarreira ) sugeriu o seguinte:

"
- elimine as linhas de IOF e acrescente-as ao valor da compra;
- multiplique as linhas de U$ já com o IOF.
  "

Eu (josecoelho) costumo catalogar o IOF como imposto mesmo, mas se mais pessoas tiverem interesse neste comportamento. É possível implementar esta funcionalidade.

Os interessados, por favor adicionar um comentário nesta tarefa pedindo pela implementação.

**Comment by jfneis** [comment]
Eu acabo classificando como imposto ou como a compra, depende do tamanho. Pra gastos menores (Google Drive, coisas assim), largo com "Tarifa Bancária", mas nas vezes que ocorre uma compra maior vou atrás e classifico junto com o gasto ("Viagens", por exemplo).

**Comment by LeoFCardoso** [comment]
-1
Prefiro associar IOF a uma conta separada, de pagamento de impostos.
