### ISSUE TITLE
Problema na identificação ao importar multiplos cartões

### ISSUE THREAD

**Issue by josecoelho** [josecoelho/bbvisa2ofx#5]
Juca Mesquita (https://www.facebook.com/JMesquitaFilho) relatou o seguinte:

"Tenho quatro cartões no BB. Dois Visa e dois Máster, vinculados a duas contas correntes diferentes.
Faço a conversão de cada um dos extratos txt no aplicativo bbvisa2ofx mas, quando importo para o Money, ele leva todos os extratos para uma só conta de cartão, não reconhecendo cada uma das quatro individualmente."

**Comment by josecoelho** [comment]
O problema foi encontrado e corrigido no commit https://github.com/josecoelho/bbvisa2ofx/commit/0add7ec77071532fd8a408bc03dc0db109f53b95

O número do cartão, que deveria estar sendo usado na tag ACCTID para identificar a conta estava sendo ignorado.

O Juca vai testar para validar a solução.

**Comment by JucaMesquita** [comment]
Testei o aplicativo com as alterações e os arquivos sao importados normalmente no MS Money. Show!!!
