### ISSUE TITLE
No more year on transactions?

### ISSUE THREAD

**Issue by LeoFCardoso** [josecoelho/bbvisa2ofx#9]
This month, BB file has no year in lines with transactions. Due to this change, bbvisa2ofx cannot parse lines and generate an empty OFX file.

Can you confirm this bug in your account? What does BB want stripping year from dates? :(

**Comment by josecoelho** [comment]
Confirmed... I`ll fix that...

**Comment by josecoelho** [comment]
Fixed and published!

Can you check that?
Thanks!

**Comment by LeoFCardoso** [comment]
Thank you for the fast fix. It works, but OFX generated file has no year in transactions. I thing bbvisa2ofx should guess the correct year based on a parameter (for instance, named "today"). Transactions in months past "today" will carry the year in "today" date and transactions with months in future than "today" will carry the "year-1".

for instance: bbvisa2ofx_cli --today 2014-09-02 fatura.txt

Result:
01/01 -> 01/01/2014
30/08 -> 30/08/2014
20/12 -> 20/12/2013
31/12 -> 31/12/2013

...

**Comment by josecoelho** [comment]
I agree. I'll fix that as soon as possible.

Thanks for your feedback!

José Coelho / Software Developer
55 48 9111 7777/ contato@josecoelho.com

http://josecoelho.com

[image: Google Plus] https://plus.google.com/+josecoelho-com [image:
Linkedin] http://br.linkedin.com/in/josercoelho/ [image: Skype]

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

2014-09-02 9:02 GMT-03:00 Leonardo notifications@github.com:
